apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-production
  labels:
    app: hello-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-production
  template:
    metadata:
      labels:
        app: hello-production
    spec:
      containers:
        - name: hello
          image: nginxdemos/hello:0.3
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-production
spec:
  type: ClusterIP
  selector:
    app: hello-production
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
